name = "fig-dev"
main = "src/worker.js"
compatibility_date = "2024-01-04"
workers_dev = true

[placement]
mode = "smart"

# 本地开发环境变量
# 注意：这些是示例值，请根据您的实际环境修改
[vars]
PASSWORD = "dev-password-change-me"
THEME = "http://localhost:5173"
SLUG_LENGTH = 5

# 本地开发需要配置以下变量（请取消注释并填入真实值）
# CF_API_TOKEN = "your-dev-api-token" 
# CF_ACCOUNT_ID = "your-account-id"

# 开发环境数据库（建议使用独立的开发数据库）
# 请取消注释并配置您的开发数据库
# [[d1_databases]]
# binding = "SQLITE" 
# database_name = "slug-dev"
# database_id = "your-dev-database-id"

# 开发环境Analytics（可选）
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "fig_url_analytics_dev"